print("this is actually kinda fun ngl")
print("this is still kinda fun :)")
print("third time's the charm haha")
print("guys its getting a bit redundant now")
print("did you guys ask for 5 more commits because its task 5?")
